const galleryContent  = {
    'Character':[
        {'src': "personajes/skulliver-white.png", 'name':'Skulliver', 'alt': "current character"},
        {'src': "personajes/skulliver-blue.png", 'name':'Skulliver', 'alt': "current character"},
        {'src': "personajes/skulliver-yellow.png", 'name':'Skulliver', 'alt': "current character"},
        {'src': "personajes/terry-blue.png", 'name':'Terry', 'alt': "current character"},
        {'src': "personajes/terry-panda.png", 'name':'Terry Panda', 'alt': "current character"},
        {'src': "personajes/terry-pardo.png", 'name':'Terry Pardo', 'alt': "current character"},
        {'src': "personajes/terry-polar.png", 'name':'Terry Polar', 'alt': "current character"},
        {'src': "personajes/allen-blue.png", 'name':'Allen', 'alt': "current character"},
        {'src': "personajes/allen-gray.png", 'name':'Allen', 'alt': "current character"},
        {'src': "personajes/allen-green.png", 'name':'Allen', 'alt': "current character"},
        {'src': "personajes/bumi-brown.png", 'name':'Bumi', 'alt': "current character"},
        {'src': "personajes/bumi-yellow.png", 'name':'Bumi', 'alt': "current character"},
        {'src': "personajes/bumi-white.png", 'name':'Bumi', 'alt': "current character"},
        {'src': "personajes/catherine-black.png", 'name':'Catherine', 'alt': "current character"},
        {'src': "personajes/catherine-orange.png", 'name':'Catherine', 'alt': "current character"},
        {'src': "personajes/don-brown.png", 'name':'Don', 'alt': "current character"},
        {'src': "personajes/don-doberman.png", 'name':'Don', 'alt': "current character"},
        {'src': "personajes/horacio-brown.png", 'name':'Horacio', 'alt': "current character"},
        {'src': "personajes/horacio-blue.png", 'name':'Horacio', 'alt': "current character"},
        {'src': "personajes/robberto-blue.png", 'name':'Robberto', 'alt': "current character"},
        {'src': "personajes/robberto-gray.png", 'name':'Robberto', 'alt': "current character"},
        {'src': "personajes/robberto-yellow.png", 'name':'Robberto', 'alt': "current character"},
        {'src': "personajes/jackson-orange.png", 'name':'Jackson', 'alt': "current character"},
        {'src': "personajes/jackson-blue.png", 'name':'Jackson', 'alt': "current character"},
    ],
    'Hat':[
        {'src': "gorros/sombrero-mago-azul.png", 'name':'sombrero mago azul', 'alt': "current hat"},
        {'src': "gorros/sombrero-mago-negro.png", 'name':'sombrero mago negro', 'alt': "current hat"},
        {'src': "gorros/sombrero-mago-violeta.png", 'name':'sombrero mago violeta', 'alt': "current hat"},
        {'src': "gorros/gorro-baseball-azul.png", 'name':'gorro baseball azul', 'alt': "current hat"},
        {'src': "gorros/gorro-baseball-rojo.png", 'name':'gorro baseball rojo', 'alt': "current hat"},
        {'src': "gorros/gorro-baseball-rosa.png", 'name':'gorro baseball rosa', 'alt': "current hat"},
        {'src': "gorros/gorro-navideno.png", 'name':'gorro navideno', 'alt': "current hat"},
        {'src': "gorros/cresta-azul.png", 'name':'cresta azul', 'alt': "current hat"},
        {'src': "gorros/cresta-roja.png", 'name':'cresta roja', 'alt': "current hat"},
        {'src': "gorros/cresta-verde.png", 'name':'cresta verde', 'alt': "current hat"},
        {'src': "gorros/sombrero-corsario.png", 'name':'sombrero pirata corsario', 'alt': "current hat"},
        {'src': "gorros/sombrero-pirata.png", 'name':'sombrero pirata', 'alt': "current hat"},
        {'src': "gorros/sombrero-cowboy.png", 'name':'sombrero cowboy', 'alt': "current hat"},
        {'src': "gorros/sombrero-fedora.png", 'name':'sombrero cowboy fedora', 'alt': "current hat"},
        {'src': "gorros/top-hat-negro.png", 'name':'sombrero tpo negro', 'alt': "current hat"},
        {'src': "gorros/top-hat-rojo.png", 'name':'sombrero top rojo', 'alt': "current hat"},
        {'src': "gorros/top-hat-violeta.png", 'name':'sombrero top violeta', 'alt': "current hat"},
        {'src': "gorros/unicuerno-amarillo.png", 'name':'unicuerno amarillo', 'alt': "current hat"},
        {'src': "gorros/unicuerno-azul.png", 'name':'unicuerno azul', 'alt': "current hat"},
        {'src': "gorros/unicuerno-blanco.png", 'name':'unicuerno blanco', 'alt': "current hat"},
        {'src': "gorros/unicuerno-rosa.png", 'name':'unicuerno rosa', 'alt': "current hat"},
        {'src': "gorros/fez.png", 'name':'fez', 'alt': "current hat"},
        {'src': "gorros/cuernos-marrones.png", 'name':'cuernos marrones', 'alt': "current hat"},
        {'src': "gorros/cuernos-rojos.png", 'name':'cuernos rojos', 'alt': "current hat"},
        {'src': "gorros/cuernos-negros.png", 'name':'cuernos negros', 'alt': "current hat"},
        {'src': "gorros/cuernos-violetas.png", 'name':'cuernos violeta', 'alt': "current hat"},
        {'src': "gorros/gorro-cumple.png", 'name':'gorro cumple', 'alt': "current hat"}
    ],
    'Glasses':[
        {'src': "lentes/potter-marron.png", 'name':'potter marron', 'alt': "current glasses"},
        {'src': "lentes/potter-negro.png", 'name':'potter negro', 'alt': "current glasses"},
        {'src': "lentes/aviador.png", 'name':'aviador', 'alt': "current glasses"},
        {'src': "lentes/parche.png", 'name':'parche', 'alt': "current glasses"},
        {'src': "lentes/monoculo.png", 'name':'monoculo', 'alt': "current glasses"},
        {'src': "lentes/lentes-sol.png", 'name':'sol rojos', 'alt': "current glasses"},
        {'src': "lentes/lentes-sol-negros.png", 'name':'sol negros', 'alt': "current glasses"}

    ],
    'Other':[
        {'src': "otros/chiva-marron.png", 'name':'chiva marron', 'alt': "current misc"},
        {'src': "otros/chiva-negra.png", 'name':'chiva negra', 'alt': "current misc"},
        {'src': "otros/mostacho-marron.png", 'name':'mostacho marron', 'alt': "current misc"},
        {'src': "otros/mostacho-negro.png", 'name':'mostacho negro', 'alt': "current misc"},
        {'src': "otros/nariz-payaso.png", 'name':'nariz payaso', 'alt': "current misc"},
        {'src': "otros/monio-azul.png", 'name':'monio azul', 'alt': "current misc"},
        {'src': "otros/monio-rojo.png", 'name':'monio rojo', 'alt': "current misc"},
        {'src': "otros/monio-rosa.png", 'name':'monio rosa', 'alt': "current misc"},
        {'src': "otros/lips-red.png", 'name':'labios rojos', 'alt': "current misc"},
        {'src': "otros/lips-black.png", 'name':'labios negros', 'alt': "current misc"}
    ],
    'Other2': [
        {'src': "otros/chiva-marron.png", 'name':'chiva marron', 'alt': "current misc"},
        {'src': "otros/chiva-negra.png", 'name':'chiva negra', 'alt': "current misc"},
        {'src': "otros/mostacho-marron.png", 'name':'mostacho marron', 'alt': "current misc"},
        {'src': "otros/mostacho-negro.png", 'name':'mostacho negro', 'alt': "current misc"},
        {'src': "otros/nariz-payaso.png", 'name':'nariz payaso', 'alt': "current misc"},
        {'src': "otros/monio-azul.png", 'name':'monio azul', 'alt': "current misc"},
        {'src': "otros/monio-rojo.png", 'name':'monio rojo', 'alt': "current misc"},
        {'src': "otros/monio-rosa.png", 'name':'monio rosa', 'alt': "current misc"},
        {'src': "otros/lips-red.png", 'name':'labios rojos', 'alt': "current misc"},
        {'src': "otros/lips-black.png", 'name':'labios negros', 'alt': "current misc"}
    ]
}