const galleryContent  = {
    'Character':[
      {'src': "personajes/skulliver-white.png", 'name':'Skulliver', 'alt': "current character"},
      {'src': "personajes/skulliver-blue.png", 'name':'Skulliver', 'alt': "current character"},
      {'src': "personajes/skulliver-yellow.png", 'name':'Skulliver', 'alt': "current character"},
      {'src': "personajes/terry-blue.png", 'name':'Terry', 'alt': "current character"},
      {'src': "personajes/terry-panda.png", 'name':'Terry Panda', 'alt': "current character"},
      {'src': "personajes/terry-pardo.png", 'name':'Terry Pardo', 'alt': "current character"},
      {'src': "personajes/terry-polar.png", 'name':'Terry Polar', 'alt': "current character"},
      {'src': "personajes/allen-blue.png", 'name':'Allen', 'alt': "current character"},
      {'src': "personajes/allen-gray.png", 'name':'Allen', 'alt': "current character"},
      {'src': "personajes/allen-green.png", 'name':'Allen', 'alt': "current character"},
      {'src': "personajes/bumi-brown.png", 'name':'Bumi', 'alt': "current character"},
      {'src': "personajes/bumi-yellow.png", 'name':'Bumi', 'alt': "current character"},
      {'src': "personajes/bumi-white.png", 'name':'Bumi', 'alt': "current character"},
      {'src': "personajes/catherine-black.png", 'name':'Catherine', 'alt': "current character"},
      {'src': "personajes/catherine-orange.png", 'name':'Catherine', 'alt': "current character"},
      {'src': "personajes/don-brown.png", 'name':'Don', 'alt': "current character"},
      {'src': "personajes/don-doberman.png", 'name':'Don', 'alt': "current character"},
      {'src': "personajes/horacio-brown.png", 'name':'Horacio', 'alt': "current character"},
      {'src': "personajes/horacio-blue.png", 'name':'Horacio', 'alt': "current character"},
      {'src': "personajes/robberto-blue.png", 'name':'Robberto', 'alt': "current character"},
      {'src': "personajes/robberto-gray.png", 'name':'Robberto', 'alt': "current character"},
      {'src': "personajes/robberto-yellow.png", 'name':'Robberto', 'alt': "current character"},
      {'src': "personajes/jackson-orange.png", 'name':'Jackson', 'alt': "current character"},
      {'src': "personajes/jackson-blue.png", 'name':'Jackson', 'alt': "current character"},
    ],
    'Hat':[
        {'src': "gorros/sombrero-mago-azul.png", 'alt': "current hat"},
        {'src': "gorros/sombrero-mago-negro.png", 'alt': "current hat"},
        {'src': "gorros/sombrero-mago-violeta.png", 'alt': "current hat"},
        {'src': "gorros/gorro-baseball-azul.png", 'alt': "current hat"},
        {'src': "gorros/gorro-baseball-rojo.png", 'alt': "current hat"},
        {'src': "gorros/gorro-baseball-rosa.png", 'alt': "current hat"},
        {'src': "gorros/gorro-navideno.png", 'alt': "current hat"},
        {'src': "gorros/cresta-azul.png", 'alt': "current hat"},
        {'src': "gorros/cresta-roja.png", 'alt': "current hat"},
        {'src': "gorros/cresta-verde.png", 'alt': "current hat"},
        {'src': "gorros/sombrero-corsario.png", 'alt': "current hat"},
        {'src': "gorros/sombrero-pirata.png", 'alt': "current hat"},
        {'src': "gorros/sombrero-cowboy.png", 'alt': "current hat"},
        {'src': "gorros/sombrero-fedora.png", 'alt': "current hat"},
        {'src': "gorros/top-hat-negro.png", 'alt': "current hat"},
        {'src': "gorros/top-hat-rojo.png", 'alt': "current hat"},
        {'src': "gorros/top-hat-violeta.png", 'alt': "current hat"},
        {'src': "gorros/unicuerno-amarillo.png", 'alt': "current hat"},
        {'src': "gorros/unicuerno-azul.png", 'alt': "current hat"},
        {'src': "gorros/unicuerno-blanco.png", 'alt': "current hat"},
        {'src': "gorros/fez.png", 'alt': "current hat"},
        {'src': "gorros/cuernos-marrones.png", 'alt': "current hat"},
        {'src': "gorros/cuernos-rojos.png", 'alt': "current hat"},
        {'src': "gorros/cuernos-negros.png", 'alt': "current hat"},
        {'src': "gorros/cuernos-violetas.png", 'alt': "current hat"},
        {'src': "gorros/gorro-cumple.png", 'alt': "current hat"}
    ],
    'Glasses':[
        {'src': "lentes/potter-marron.png", 'alt': "current glasses"},
        {'src': "lentes/potter-negro.png", 'alt': "current glasses"},
        {'src': "lentes/aviador.png", 'alt': "current glasses"},
        {'src': "lentes/parche.png", 'alt': "current glasses"},
        {'src': "lentes/monoculo.png", 'alt': "current glasses"},
        {'src': "lentes/lentes-sol.png", 'alt': "current glasses"},
        {'src': "lentes/lentes-sol-negros.png", 'alt': "current glasses"}

    ],
    'Other':[
        {'src': "otros/chiva-marron.png", 'alt': "current misc"},
        {'src': "otros/chiva-negra.png", 'alt': "current misc"},
        {'src': "otros/mostacho-marron.png", 'alt': "current misc"},
        {'src': "otros/mostacho-negro.png", 'alt': "current misc"},
        {'src': "otros/nariz-payaso.png", 'alt': "current misc"},
        {'src': "otros/monio-azul.png", 'alt': "current misc"},
        {'src': "otros/monio-rojo.png", 'alt': "current misc"},
        {'src': "otros/monio-rosa.png", 'alt': "current misc"},
        {'src': "otros/lips-red.png", 'alt': "current misc"},
        {'src': "otros/lips-black.png", 'alt': "current misc"}
    ]
}